In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
#process the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
#split the data in training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
    
with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)
    
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Regression Problem Statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1) #output layer for regression
])

# compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

c:\Users\shash\.conda\envs\myenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [19]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [20]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100371.6250 - mae: 100371.6250 - val_loss: 98493.3906 - val_mae: 98493.3906
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99548.2812 - mae: 99548.2812 - val_loss: 96839.0469 - val_mae: 96839.0469
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96687.7109 - mae: 96687.7109 - val_loss: 92649.4219 - val_mae: 92649.4219
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 91107.6172 - mae: 91107.6172 - val_loss: 85778.3125 - val_mae: 85778.3125
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83068.3281 - mae: 83068.3281 - val_loss: 77002.2031 - val_mae: 77002.2031
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 73799.1250 - mae: 73799.1250 - val_loss: 67995.0625 - val_mae: 67995.0625
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 64955.6953 - mae: 64955.6953 - val_loss: 60362.0273 - val_mae: 60362.0273
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 58100.3008 - mae: 58100.3008 - val_loss: 55100.4805 - val_mae: 55100.4805
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53801.9219 - mae: 53801.9219 - val_loss: 52333.7891 - val_mae: 52333.7891
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51654.5586 - mae: 51654.5586 - val_loss: 51228.9805 - val_mae: 51228.9805
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50784.3281 - mae: 50784.3281 - val_loss: 50934.6367 - val_mae: 50934.6367
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50472.6875 - mae: 50472.6875 - val_loss: 50826.7539 - val_mae: 50826.7539
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50327.1992 - mae: 50327.1992 - val_loss: 50780.7305 - val_mae: 50780.7305
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50245.5977 - mae: 50245.5977 - val_loss: 50745.3867 - val_mae: 50745.3867
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50188.7109 - mae: 50188.7109 - val_loss: 50707.3867 - val_mae: 50707.3867
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50141.0039 - mae: 50141.0039 - val_loss: 50679.4609 - val_mae: 50679.4609
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50099.1172 - mae: 50099.1172 - val_loss: 50660.1523 - val_mae: 50660.1523
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50060.0469 - mae: 50060.0469 - val_loss: 50642.5625 - val_mae: 50642.5625
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50028.1445 - mae: 50028.1445 - val_loss: 50618.4414 - val_mae: 50618.4414
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50003.5703 - mae: 50003.5703 - val_loss: 50601.5938 - val_mae: 50601.5938
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49973.1133 - mae: 49973.1133 - val_loss: 50577.8945 - val_mae: 50577.8945
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49948.0977 - mae: 49948.0977 - val_loss: 50559.8633 - val_mae: 50559.8633
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49923.1055 - mae: 49923.1055 - val_loss: 50548.2461 - val_mae: 50548.2461
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49901.3945 - mae: 49901.3945 - val_loss: 50535.0195 - val_mae: 50535.0195
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49877.0859 - mae: 49877.0859 - val_loss: 50523.1328 - val_mae: 50523.1328
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49859.3359 - mae: 49859.3359 - val_loss: 50501.5508 - val_mae: 50501.5508
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49838.5430 - mae: 49838.5430 - val_loss: 50506.4375 - val_mae: 50506.4375
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49819.0000 - mae: 49819.0000 - val_loss: 50480.2891 - val_mae: 50480.2891
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49805.7031 - mae: 49805.7031 - val_loss: 50469.5742 - val_mae: 50469.5742
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49787.6367 - mae: 49787.6367 - val_loss: 50456.6250 - val_mae: 50456.6250
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49772.5352 - mae: 49772.5352 - val_loss: 50453.7578 - val_mae: 50453.7578
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49753.5547 - mae: 49753.5547 - val_loss: 50449.5898 - val_mae: 50449.5898
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49741.6406 - mae: 49741.6406 - val_loss: 50442.9648 - val_mae: 50442.9648
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49726.7852 - mae: 49726.7852 - val_loss: 50433.8398 - val_mae: 50433.8398
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49712.0312 - mae: 49712.0312 - val_loss: 50431.4062 - val_mae: 50431.4062
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49702.3438 - mae: 49702.3438 - val_loss: 50424.8672 - val_mae: 50424.8672
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49688.4844 - mae: 49688.4844 - val_loss: 50408.5859 - val_mae: 50408.5859
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49674.5156 - mae: 49674.5156 - val_loss: 50396.6992 - val_mae: 50396.6992
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49666.1797 - mae: 49666.1797 - val_loss: 50399.1523 - val_mae: 50399.1523
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49654.5977 - mae: 49654.5977 - val_loss: 50389.4375 - val_mae: 50389.4375
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49643.9805 - mae: 49643.9805 - val_loss: 50384.2109 - val_mae: 50384.2109
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49633.1836 - mae: 49633.1836 - val_loss: 50378.3320 - val_mae: 50378.3320
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49624.8203 - mae: 49624.8203 - val_loss: 50385.7422 - val_mae: 50385.7422
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49616.9688 - mae: 49616.9688 - val_loss: 50377.0234 - val_mae: 50377.0234
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49608.0547 - mae: 49608.0547 - val_loss: 50376.8242 - val_mae: 50376.8242
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49597.4961 - mae: 49597.4961 - val_loss: 50374.7227 - val_mae: 50374.7227
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49586.6602 - mae: 49586.6602 - val_loss: 50376.8438 - val_mae: 50376.8438
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49581.5547 - mae: 49581.5547 - val_loss: 50376.1016 - val_mae: 50376.1016
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49576.1562 - mae: 49576.1562 - val_loss: 50376.3555 - val_mae: 50376.3555
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49563.9766 - mae: 49563.9766 - val_loss: 50366.0898 - val_mae: 50366.0898
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49557.9492 - mae: 49557.9492 - val_loss: 50372.0352 - val_mae: 50372.0352
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49552.8164 - mae: 49552.8164 - val_loss: 50362.1602 - val_mae: 50362.1602
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49542.6523 - mae: 49542.6523 - val_loss: 50370.9258 - val_mae: 50370.9258
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49538.1875 - mae: 49538.1875 - val_loss: 50373.6875 - val_mae: 50373.6875
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49531.8086 - mae: 49531.8086 - val_loss: 50367.6133 - val_mae: 50367.6133
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49527.6953 - mae: 49527.6953 - val_loss: 50373.1484 - val_mae: 50373.1484
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49516.9766 - mae: 49516.9766 - val_loss: 50385.6328 - val_mae: 50385.6328
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49510.7539 - mae: 49510.7539 - val_loss: 50381.5117 - val_mae: 50381.5117
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49506.4336 - mae: 49506.4336 - val_loss: 50381.9648 - val_mae: 50381.9648
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49497.9375 - mae: 49497.9375 - val_loss: 50364.5781 - val_mae: 50364.5781
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49494.2656 - mae: 49494.2656 - val_loss: 50372.0508 - val_mae: 50372.0508
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49487.7422 - mae: 49487.7422 - val_loss: 50373.9766 - val_mae: 50373.9766

In [31]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [37]:
import os, subprocess, sys, time, urllib.request

log_dir = os.path.join(os.getcwd(), 'regressionlogs', 'fit')
cmd = [sys.executable, '-m', 'tensorboard.main', '--logdir', log_dir, '--host', '127.0.0.1', '--port', '6006']
subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL)
time.sleep(3)
print('TensorBoard is running at http://127.0.0.1:6006/')

TensorBoard is running at http://127.0.0.1:6006/

In [38]:
# Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 50362.1602 - mae: 50362.1602
Test MAE : 50362.16015625

In [39]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.